# Generated by Django 2.1.2 on 2018-10-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ints1', models.CharField(default='', max_length=250)),
                ('ints2', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('link', models.CharField(default='', max_length=250)),
                ('category', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(default='', max_length=250)),
                ('LastName', models.CharField(default='', max_length=250)),
                ('Email', models.CharField(default='', max_length=250)),
                ('interest1', models.CharField(default='', max_length=250)),
                ('interest2', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
